#!/bin/sh

usage="Usage: $(basename $0) [FILES]: assists efficiently and conveniently the commit of specified file(s)."


# Select relevant version control client:
vcs_tool="svn"

if [ -d "CVS" ]; then
	vcs_tool="cvs"
fi


target=$*
arrow="---------------------> "

echo "$arrow Showing diff for <${target}>:"

# CVS diff returns 1 whereas ok:
if [ ${vcs_tool} = "cvs" ]; then

	${vcs_tool} diff "${target}"
	echo "${arrow} Committing-in <${target}>:"
	${vcs_tool} ci "${target}"

	echo "...done"

elif [ -d ".svn" ]; then

	if ${vcs_tool} diff "${target}" | more; then

		echo "${arrow} Committing-in <${target}>:"
		${vcs_tool} ci "${target}"

		echo "...done"

	fi

else


	if [ -z "${target}" ]; then

		# If no argument has been specified, default to incremental commits for
		# all:
		#
		dci-all

	else

		# In case was not added yet, to see the diffs at next stage:
		git add "${target}"

		# We want to see what we are about to commit:
		# (not wanting the pager to truncate longer lines)

		# Ex: version 1.7.2.5 does not support minimal:
		#GIT_PAGER='' git diff --staged --minimal ${target}
		GIT_PAGER='' git diff --staged "${target}"

		echo "${arrow} Committing-in <${target}>:"
		git commit "${target}"

		if [ ! $? -eq 0 ]; then

			echo "Commit aborted for ${target}, unstaging it." 1>&2

			git reset HEAD "${target}"

		fi

	fi

fi
