#!/bin/sh

# Useful to check-in efficiently (fast):


# Select relevant version control client:
TOOL="svn"

if [ -d 'CVS' ] ; then
	TOOL="cvs"
fi


target=$*
arrow="---------------------> "

echo "$arrow Showing diff for <$target>:"

# CVS diff returns 1 whereas ok:
if [ ${TOOL} = "cvs" ] ; then

	${TOOL} diff $target
	echo "$arrow Committing-in <$target>:"
	${TOOL} ci $target

	echo "...done"

elif [ -d ".svn" ] ; then
		
	if ${TOOL} diff $target | more ; then

		echo "$arrow Committing-in <$target>:"
		${TOOL} ci $target
		
		echo "...done"

	fi
	
else

	if [ -n "$target" ] ; then
		
	    # In case was not added yet, to see the diffs at next stage:
		git add $target

	fi
	
	# We want to see what we are about to commit:
	git diff --staged $target

	echo "$arrow Committing-in <$target>:"
	git commit $target
	
fi
