#!/bin/sh

# Select relevant version control client:

if [ -d 'CVS' ] ; then

	cvs diff $* | more

elif [ -d '.svn' ] ; then

	svn diff $* | more

else

	# We prefer here comparing the current working version with the commit, not
	# with the origin:
	#
	git diff $*

	# We prefer here seeing the changes you staged for the next commit relative
	# to the current head:
	#
	#git diff --staged $*


fi
