#!/bin/sh

# By default, shows the differences between the current versions of the files on
# the filesystem and the staged ones (i.e. the changes that might be added),
# using a graphical diff tool (typically meld).


# See also: 'dif'.


# Select relevant version control client:

if [ -d 'CVS' ] ; then

	cvs diff $* | more

elif [ -d '.svn' ] ; then

	svn diff $* | more

else

	# We prefer here comparing the current working version (on the filesystem)
	# with the specified commit (if not specified, the latest one), not with any
	# staged version (see 'difs' fort that):
	#
	args="$*"

	if [ -z "${args}" ] ; then

		# We find it more convenient to only start from the current directory,
		# rather than inspecting the full repository (hence the dot):
		git difftool .

	else

		git difftool $*

	fi

fi
