#!/bin/sh

# By default, shows the differences between the staged files and their committed
# version.


# More precisely: shows (regardless of the current versions available on the
# filesystem) the changes that have been staged (for the next commit) relative
# to the specified commit, which is by default the latest one.

# See also: 'dif'.


args="$*"

if [ -z "${args}" ] ; then

	# We find it more convenient to only start from the current directory,
	# rather than inspecting the full repository (hence the dot):
	git diff --cached .

else

	git diff --cached $*

fi
