#!/bin/sh

VERSION_FILENAME="version.inc"

USAGE="Usage: "`basename $0`" <major> <minor> <release>: generates a file named '$VERSION_FILENAME' which can set version numbers both when sourced by a shell script (setting the MAJOR_VERSION, MINOR_VERSION and RELEASE variables appropriately) and included by a m4 script. This is useful as a workaround to Autoconf AC_INIT behaviour."

if test "$#" -ne 3 ; then
	echo $USAGE 1>&2
	exit 1
fi 

echo "dnl=\"This rather convoluted file allows to centralize version numbers while \"" > $VERSION_FILENAME

echo "dnl=\"being able to be both sourced by shell scripts and included by m4.\"" >> $VERSION_FILENAME

echo "dnl=\"It can be generated by the 'generateVersionFile.sh' script.\"" >> $VERSION_FILENAME

echo "dnl=; MAJOR=$1; MINOR=$2; RELEASE=$3 ; RELEASE_DATE=\""`date '+%A, %B %e, %Y'`"\"; m4_hiding_string=\"\\" >> $VERSION_FILENAME

echo "$1.$2.$3" >> $VERSION_FILENAME
echo "dnl \"" >> $VERSION_FILENAME

echo "'$VERSION_FILENAME' has been generated."


