#!/bin/sh


NO_X_OPT="--noX"
SHOW_OPT="--display"


USAGE="
Usage: $(basename $0) [${NO_X_OPT}] [${SHOW_OPT}] [-h|--help] [-e|--emacs] [-n|--nedit] [-f|--find] [-s|--standalone] file1 file2 ...:

  Opens the set of specified files with the 'best' available editor.

  Options are:
	  '${NO_X_OPT}' to prevent selecting a graphical editor, notably if there is no available X display
	  '${SHOW_OPT}' to display only the chosen settings (not executing them)
	  '-e' or '--emacs' to prefer emacs over all other editors (the default)
	  '-n' or '--nedit' to prefer nedit over all other editors
	  '-f' or '--find' to first look-up specified file from current directory, before opening it
	  '-s' or '--standalone' to prefer not using the server-based version of the selected editor, if applicable (useful to avoid reusing any already opened window)
	  '-l' or '--locate' to open the single file (if any) found thanks to 'locate'
"

# Note: a special syntax is recognised as well: 'n A_FILE -s', which is
# convenient when wanting to open a file yet thinking last that this should be
# done in another window.


# Defaults:
prefer_emacs=0
prefer_nedit=1

# Tells whether we want to launch a standalone editor (default: no):
standalone=1

run_in_background=0

# Function section.


chooseJedit()
{

	# jedit:
	JEDIT=$(which jedit 2>/dev/null | grep -v ridiculously 2>/dev/null)

	if [ -x "${JEDIT}" ] ; then
		EDITOR="${JEDIT}"
		EDITOR_SHORT_NAME="jedit"
		MULTI_WIN=0
	fi

}



chooseNedit()
{

	# nedit:

	# Many names for nedit client/server: gentoo...
	NEDITC_GENTOO=$(which neditc 2>/dev/null | grep -v ridiculously 2>/dev/null)

	# ...debian...
	NEDITC_DEBIAN=$(which nedit-nc 2>/dev/null | grep -v ridiculously 2>/dev/null)

	# ...and others (nc can be netcat too)
	NC=$(which nc 2>/dev/null | grep -v ridiculously 2>/dev/null)

	# Basic nedit, one full process by window:
	NEDIT=$(which nedit 2>/dev/null | grep -v ridiculously 2>/dev/null)


	# Sets of X parameters common to all nedit members:
	NEDIT_FAMILY_OPT="-create -xrm nedit*text.background:black -xrm nedit*text.foreground:white -xrm nedit*text.lineNumForeground:red -xrm nedit*text.cursorForeground:white"

	NEDIT_NC_OPT="-noask"

	if [ -x "${NEDIT}" ] ; then
		EDITOR="${NEDIT} ${NEDIT_FAMILY_OPT}"
		EDITOR_SHORT_NAME="nedit"
		MULTI_WIN=0
	fi

	if [ -x "${NC}" ] ; then
		if ${NC} -h 2>/dev/null; then
		 # Not netcat:
			EDITOR="${NC} ${NEDIT_FAMILY_OPT} ${NEDIT_NC_OPT}"
			EDITOR_SHORT_NAME="nc"
			MULTI_WIN=0
	 # else: the nc being detected is netcat, not nedit tool: do nothing here.
		fi
	fi

	if [ -x "${NEDITC_GENTOO}" ] ; then
		EDITOR="${NEDITC_GENTOO} ${NEDIT_FAMILY_OPT}"
		EDITOR_SHORT_NAME="neditc"
		MULTI_WIN=0
	fi

	if [ -x "${NEDITC_DEBIAN}" ] ; then
		EDITOR="${NEDITC_DEBIAN} ${NEDIT_FAMILY_OPT} ${NEDIT_NC_OPT}"
		EDITOR_SHORT_NAME="nedit-nc"
		MULTI_WIN=0
	fi

}




# For the *emacs, we use a window width of 83 instead of 80 to compensate
# for the line numbers. However the length of that number depends on the
# number of lines (ex: more than 1000 lines implies 4 digits on the left).

chooseXemacs()
{

	# xemacs:

	XEMACS=$(which xemacs 2>/dev/null | grep -v ridiculously 2>/dev/null)

	if [ -x "${XEMACS}" ] ; then
		EDITOR="${XEMACS} --geometry=83x60 "
		EDITOR_SHORT_NAME="xemacs"
		MULTI_WIN=0
	fi

}



chooseEmacs()
{

	# emacs: (allows, if no emacs server is running, to run a standalone
	# emacs instead, which itself will be a server thanks to its
	# '(server-start)' configuration.

	EMACS=$(which emacs 2>/dev/null | grep -v ridiculously 2>/dev/null)

	if [ -x "${EMACS}" ] ; then

		ALTERNATE_EDITOR="/bin/emacs --geometry=83x60"

		if [ $standalone -eq 1 ] ; then

			EMACS_CLIENT="/bin/emacsclient"

			if [ ! -x "${EMACS_CLIENT}" ] ; then

				EMACS_CLIENT="/usr/bin/emacsclient"

				if [ ! -x "${EMACS_CLIENT}" ] ; then

					echo " Error, no emacs client available." 1>&2
					exit 55

				fi

			fi

			# Default:
			EDITOR="${EMACS_CLIENT} --alternate-editor=emacs"

		else

			EMACS="/bin/emacs"

			if [ ! -x "${EMACS}" ] ; then

				EMACS="/usr/bin/emacs"

				if [ ! -x "${EMACS}" ] ; then

					echo " Error, no (standalone) emacs available." 1>&2
					exit 56

				fi
			fi

			EDITOR="/bin/emacs"

		fi

		VISUAL=$EDITOR
		EDITOR_SHORT_NAME="emacs"

		MULTI_WIN=0

	fi

}



chooseNano()
{

	# nano, text-based user-friendly editor:
	NANO=$(which nano 2>/dev/null | grep -v ridiculously 2>/dev/null)

	EDITOR="${NANO}"
	EDITOR_SHORT_NAME="nano"
	MULTI_WIN=1

}



chooseVim()
{

	# vi improved:
	VIM=$(which vim 2>/dev/null | grep -v ridiculously 2>/dev/null)

	EDITOR="${VIM}"
	EDITOR_SHORT_NAME="vim"
	MULTI_WIN=1

}



chooseVi()
{

	# Raw vi:
	VI=$(which vi 2>/dev/null | grep -v ridiculously 2>/dev/null)

	EDITOR="${VI}"
	EDITOR_SHORT_NAME="vi"
	MULTI_WIN=1

}



autoSelectEditor()
{

	# Take the best one (watch out the order!):

	EDITOR=""
	EDITOR_SHORT_NAME=""

	MULTI_WIN=1


	if [ "${do_X}" -eq 0 ] ; then

		if [ $prefer_emacs -eq 0 ] ; then

			if [ -z "$EDITOR" ] ; then
				chooseEmacs
			fi

			if [ -z "$EDITOR" ] ; then
				chooseXemacs
			fi

			if [ -z "$EDITOR" ] ; then
				chooseNedit
			fi

		else

			if [ $prefer_nedit -eq 0 ] ; then

				if [ -z "$EDITOR" ] ; then
					chooseNedit
				fi

				if [ -z "$EDITOR" ] ; then
					chooseEmacs
				fi

				if [ -z "$EDITOR" ] ; then
					chooseXemacs
				fi

			else

				chooseEmacs

				if [ -z "$EDITOR" ] ; then
					chooseXemacs
				fi

				if [ -z "$EDITOR" ] ; then
					chooseNedit
				fi

			fi

		fi

	fi

	if [ -n "$EDITOR" ] ; then
		return
	fi


	if [ -x "${NANO}" ] ; then
		chooseNano
		return
	fi


	if [ -x "${VIM}" ] ; then
		chooseVim
		return
	fi


	if [ -x "${VI}" ] ; then
		chooseVi
		return
	fi

}



applyEditor()
{

	#echo "MULTI_WIN = ${MULTI_WIN}"
	#echo "EDITOR_SHORT_NAME = ${EDITOR_SHORT_NAME}"
	#echo "EDITOR = ${EDITOR}"

	# Let's hope the display is OK.

	# Open the files in parallel or sequentially:
	for f in ${PARAMETERS}; do

		if [ ! -f "$f" ] ; then

			# Sometimes a filename followed by some garbage is specified
			# (ex: a regrep might return "class_X.erl:construct");
			# Here we try to fix the filename:

			new_f=$(echo "$f"| sed 's|:.*$||1')

			if [ -f "$new_f" ] ; then

				   echo "  (non-existing file '$f' has been automatically translated to existing file '$new_f')"

				   f=$new_f

			fi

		fi

		if [ -z "${DISPLAY}" ] ; then
			echo "    Opening $f with ${EDITOR_SHORT_NAME} (no DISPLAY set)"
		else
			echo "    Opening $f with ${EDITOR_SHORT_NAME} (DISPLAY is <${DISPLAY}>)"
		fi

		if [ ${MULTI_WIN} -eq 0 ] ; then

			if [ "${EDITOR_SHORT_NAME}" = "emacs" ] ; then
				# To get rid of silly message:
				# "(emacs:12040): GLib-WARNING **: g_set_prgname() called
				# multiple times"
				${EDITOR} $f 1>/dev/null 2>&1 &

				# Small delay added, otherwise specifying multiple files
				# apparently may freeze emacs to death, loosing all pending
				# changes...
				#
				sleep 1

			else
				${EDITOR} $f 2>/dev/null &

			fi

			if [ "{EDITOR_SHORT_NAME}" = "nedit" ] ; then
				sleep 1
			fi

		else

			# As not all tools can/shall be run in background:

			if [ $run_in_background -eq 0 ] ; then

				#echo "Running ${EDITOR} in background..."
				${EDITOR} "$f" 2>/dev/null &

			else

				#echo "Running ${EDITOR} in foreground..."
				${EDITOR} "$f"

			fi

		fi

	done

}


displayEditors()
{

	# Just for the side-effect of setting their executable paths:
	chooseJedit
	chooseNedit
	chooseXemacs
	chooseEmacs
	chooseNano
	chooseVim
	chooseVi

	echo
	echo "JEDIT         = ${JEDIT}"
	echo "NEDITC_GENTOO = ${NEDITC_GENTOO}"
	echo "NEDITC_DEBIAN = ${NEDITC_DEBIAN}"
	echo "NC            = ${NC}"
	echo "NEDIT         = ${NEDIT}"
	echo "XEMACS        = ${XEMACS}"
	echo "EMACS         = ${EMACS}"
	echo "NANO          = ${NANO}"
	echo "VIM           = ${VIM}"
	echo "VI            = ${VI}"
	echo

}



# Main section.


do_X=0
do_show=1
do_force_nedit=1
do_find=1
do_locate=1


if [ "$1" = "${NO_X_OPT}" ] ; then
	do_X=1
	shift
fi


if [ "$1" = "${SHOW_OPT}" ] ; then
	do_show=0
	shift
fi


if [ "$1" = "-e" ] || [ "$1" = "--emacs" ] ; then
	prefer_emacs=1
	prefer_nedit=0
	echo "(requested to prefer emacs over other editors)"
	shift
fi


if [ "$1" = "-n" ] || [ "$1" = "--nedit" ] ; then
	prefer_emacs=0
	prefer_nedit=1
	echo "(requested to prefer nedit over other editors)"
	shift
fi


if [ "$1" = "-s" ] || [ "$1" = "--standalone" ] ; then
	standalone=0
	shift
fi

if [ "$1" = "-f" ] || [ "$1" = "--find" ] ; then
	do_find=0
	shift
fi

if [ "$1" = "-l" ] || [ "$1" = "--locate" ] ; then
	do_locate=0
	shift
fi


if [ "$1" = "--help" ] ; then
	echo "${USAGE}"
	exit 0
fi


if [ "$1" = "-h" ] ; then
	echo "${USAGE}"
	exit 0
fi


if [ -z "$1" ] ; then
	if [ ${do_show} -eq 1 ] ; then
		echo "${USAGE}"
		exit 1
	fi
fi


if [ ${do_show} -eq 0 ] ; then
	displayEditors
fi

# A problem is that if a specified file includes spaces (ex: 'hello world.txt'),
# then apparently there is not easy way in sh to preserve that space (the script
# will understand that two files are listed, 'hello' and 'world.txt').
#
# See
# https://unix.stackexchange.com/questions/131766/why-does-my-shell-script-choke-on-whitespace-or-other-special-characters for more details.


# Assigned only here to take into account the previous shifts:

# Not done anymore, as loses spaces:
#REMAINING_PARAMETERS="$@"
#echo "REMAINING_PARAMETERS = $REMAINING_PARAMETERS"

PARAMETERS=""

# Last filtering:
#for arg in $REMAINING_PARAMETERS ; do
for arg in "$@" ; do

	if [ "$arg" = "-s" ] ; then

		standalone=0

	else

		# Here $arg is still right:
		#echo "arg=$arg"

		# But then the information is lost when:
		PARAMETERS="$PARAMETERS ${arg}"

	fi

done

# Last test regarding spaces included in filenames:
#for p in ${PARAMETERS} ; do echo "- parameter: '$p'" ; done
#exit

if [ $standalone -eq 0 ] ; then

	echo "  (standalone mode activated)"

fi


if [ $do_find -eq 0 ] ; then

	# Single file assumed, any initial whitespace removed:
	target_file=$(echo "${PARAMETERS}" | sed 's|^ ||1' | sed 's|:.*$||1')
	#echo "target_file = $target_file"

	target_path=$(find . -name $target_file)

	if [ -z "${target_path}" ] ; then

		echo "  (file '$target_file' not found, nothing done)"

	else

		echo "  (file '$target_file' found as '$target_path')"

	fi

	PARAMETERS="${target_path}"

fi


if [ $do_locate -eq 0 ] ; then

	# Single file assumed, any initial whitespace removed:
	target_file=$(echo "${PARAMETERS}" | sed 's|^ ||1' | sed 's|:.*$||1')
	#echo "target_file = $target_file"

	target_path=$(/bin/locate --limit 1 --existing ${target_file})

	if [ -z "${target_path}" ] ; then

		echo "  (file '$target_file' not found, nothing done)"

	else

		echo "  (file '$target_file' found as '$target_path')"

	fi

	PARAMETERS="${target_path}"

fi




# Default:
MULTI_WIN=1


EXTENSION=$(echo $PARAMETERS| sed 's|^.*\.||1')
#EXTENSION=$(echo $1| sed 's|^.*\.||1')


#echo "PARAMETERS = $PARAMETERS"
#echo "EXTENSION = $EXTENSION"


# Deactivated for the moment:
#
#if [ "${EXTENSION}" = "erl" ] ; then
#
#	chooseJedit
#	applyEditor
#	exit 0
#
#fi

if [ "${EXTENSION}" = "pdf" ] || [ "${EXTENSION}" = "PDF" ] ; then

	EDITOR=$(which evince)
	EDITOR_SHORT_NAME="evince"
	applyEditor
	exit 0

fi


if [ "${EXTENSION}" = "png" ] ; then

	EDITOR=$(which eog)
	EDITOR_SHORT_NAME="eog"
	applyEditor
	exit 0

fi


if [ "${EXTENSION}" = "jpeg" -o "${EXTENSION}" = "jpg" ] ; then

	EDITOR=$(which eog)
	EDITOR_SHORT_NAME="eog"
	applyEditor
	exit 0

fi

# Disabled now, as we want to be able to *edit* HTML files:
#if [ "${EXTENSION}" = "html" ] ; then
#
#      EDITOR=$(which firefox)
#      EDITOR_SHORT_NAME="firefox"
#      applyEditor
#      exit 0
#
#fi

if [ "${EXTENSION}" = "ogg" ] || [ "${EXTENSION}" = "mp3" ] || [ "${EXTENSION}" = "mp4"  ] ; then

	EDITOR=$(which mplayer)
	EDITOR_SHORT_NAME="mplayer"

	# Otherwise difficult to control/stop:
	run_in_background=1

	applyEditor

	exit 0

fi


if [ "${EXTENSION}" = "dia" ] ; then

	EDITOR=$(which dia)
	EDITOR_SHORT_NAME="dia"
	applyEditor
	exit 0

fi


if [ "${EXTENSION}" = "xlsx" ] ; then

	EDITOR=$(which libreoffice)
	EDITOR_SHORT_NAME="LibreOffice"
	applyEditor
	exit 0

fi


if [ "${EXTENSION}" = "docx" ] ; then

	EDITOR=$(which libreoffice)
	EDITOR_SHORT_NAME="LibreOffice"
	applyEditor
	exit 0

fi


if [ "${EXTENSION}" = "traces" ] ; then

	LOGMX=$(which logmx.sh)

	if [ ! -x "${LOGMX}" ] ; then

		echo "  (no LogMX found, using default editor for traces)"

	else

		EDITOR="${LOGMX}"
		EDITOR_SHORT_NAME="LogMX"

	fi

	applyEditor
	exit 0

fi


autoSelectEditor

if [ ${do_show} -eq 0 ] ; then

	echo "Chosen editor: ${EDITOR_SHORT_NAME}"
	echo "Complete editor command: ${EDITOR}"
	echo "Multiwin: ${MULTI_WIN}"
	exit

fi


if [ -z "${EDITOR}" ] ; then

	echo "Error, none of the registered editors (neditc, nc, nedit, nano, vim or vi) can be used. Stopping now." 1>&2
	exit 1

fi


applyEditor
