#!/bin/sh

echo "<center>"
echo "    <table summary=\"Code\" style=\"border : none\">"
echo "        <tr>"
echo "          <td>"
echo "            <div class=\"box\">"
echo "<code><pre>"
echo ""
echo "</pre></code>"
echo "            </div>"
echo "          </td>"
echo "        </tr>"
echo "    </table>"
echo "</center>"
