#!/bin/sh

USAGE=`basename $0`"[-s|--short]: describes recursively from current directory what files are not in up-to-date state regarding the SVN repository.
The -s/--short option will not display elements that are not versioned or ignored."

short=1

if [ "$1" = "-s" ] || [ "$1" = "--short" ] ; then

	short=0

fi


# When having something like 'A  +   my-file.txt', breaks the structure:
OUTPUT=`svn status --no-ignore 2>/dev/null|sed 's|+| |1'`

#echo "OUTPUT = $OUTPUT"


# To rebuild a correctly formatted output (since newlines are eaten when
# re-reading the variable), multiple sed must be used:


ADDED=$(echo "${OUTPUT}" | grep '^A' | awk '{print $2}')

#echo "ADDED = $ADDED"
#exit


ONCONFLICT=$(echo "${OUTPUT}" | grep '^C' | awk '{print $2}')


REMOVED=$(echo "${OUTPUT}" | grep '^D' | awk '{print $2}')


MODIFIED=$(echo "${OUTPUT}" | grep '^M' | awk '{print $2}')


REPLACED=$(echo "${OUTPUT}" | grep '^R' | awk '{print $2}')


EXTERNALDEF=$(echo "${OUTPUT}" | grep '^X' | awk '{print $2}')


UNKNOWN=$(echo "${OUTPUT}" | grep '^?' | awk '{print $2}')


INCOMPLETE=$(echo "${OUTPUT}" | grep '^!' | awk '{print $2}')


MISMATCH=$(echo "${OUTPUT}" | grep '^~' | awk '{print $2}')


IGNORED=$(echo "${OUTPUT}" | grep '^I' | awk '{print $2}')



# Most interesting last, to be obvious in a terminal print-out:

if [ -n "${ADDED}" ]; then
	echo "* Added elements:"
	for f in ${ADDED} ; do
		echo " - $f"
	done

	echo
fi


if [ -n "${REMOVED}" ]; then
	echo "* Elements scheduled for deletion:"
	for f in ${REMOVED} ; do
		echo " - $f"
	done

	echo
fi




if [ -n "${MODIFIED}" ]; then
	echo "* Modified files:"
	for f in ${MODIFIED} ; do
		echo " - $f"
	done

	echo
fi


if [ -n "${REPLACED}" ]; then
	echo "* Elements scheduled for replacement:"
	for f in ${REPLACED} ; do
		echo " - $f"
	done

	echo
fi


if [ -n "${EXTERNALDEF}" ]; then
	echo "* Elements unversioned, but related to a svn externals definition:"
	for f in ${EXTERNALDEF} ; do
		echo " - $f"
	done

	echo
fi


if [ $short -eq 1 ] ; then


	if [ -n "${UNKNOWN}" ]; then
		echo "* Elements not versioned:"
		for f in ${UNKNOWN} ; do
			echo " - $f"
		done

		echo
	fi

fi


if [ -n "${INCOMPLETE}" ]; then
	echo "* Elements incomplete:"
	for f in ${INCOMPLETE} ; do
		echo " - $f"
	done

	echo
fi


if [ -n "${MISMATCH}" ]; then
	echo "* Elements mismatched:"
	for f in ${MISMATCH} ; do
		echo " - $f"
	done

	echo
fi

if [ $short -eq 1 ] ; then

	if [ -n "${IGNORED}" ]; then
		echo "* Elements ignored:"
		for f in ${IGNORED} ; do
			echo " - $f"
		done

		echo
	fi

fi


if [ -n "${ONCONFLICT}" ]; then
	echo "* Files with conficts:"
	for f in ${ONCONFLICT} ; do
		echo " - $f"
	done

	echo
fi
